### ISSUE TITLE
Why is `content` not a property an requires attribute style binding `$=`?

### ISSUE THREAD

**Issue by lbustelo** [Juicy/juicy-html#18]
Would be nice if `content` could be set using property binding in a `dom-bind` template. Right now it requires `$=`. At the very least, the README needs to reflect that requirement.

**Comment by tomalec** [comment]
Good point @lbustelo, thanks!
I'll try to make it in some spare time. In meantime I've updated README to match current implementation.

**Comment by tomalec** [comment]
Hopefully it could benefit in performance with Polymer 1.x, the question is how it applies to Polymer 2.0 Template binding.

**Comment by tomalec** [comment]
It seems, that there is a bug, which make this one required to work, as `$=` does not work for `template` element. 
The main problem is that, we need a new name - we cannot override native `.content` property of the `HTMLTemplateElement`

@warpech, @miyconst, @lbustelo, @deadlyfingers any ideas?

I'd like to keep it short, meaningful and similar/related to `content` and `href` as they match conceptually similar thing.

**Comment by tomalec** [comment]
(work in progress is available at [`issues/18-content-property` branch](https://github.com/Juicy/juicy-html/compare/issues/18-content-property))

**Comment by tomalec** [comment]
My proposition for the new name is `href`
+ usually, that's what it is - hyperlink with reference to document to fetch template from,

 but..
-  it could look weird for inline markup.

**Comment by tomalec** [comment]
@warpech Maybe we should do it otherwise. Instead of [facing dilemma](https://github.com/Juicy/juicy-html/issues/18#issuecomment-253660930)  whether to have attribute name that matches inline  content and hyper link, and maintain hidden heuristic rules that guesses that you want to load external content. Just make it explicitly separated?
 - for external content: `href` 
 - for internal content:
   a. `content` - and don't code it just forward attribute to use native `template.content` property, just control the (auto)stamping via `stamp` attribute - https://github.com/Juicy/juicy-html/issues/10)
   b. `html` which works as before, but no longer collide with `property`
 - to avoid collisions and headache of mixing those two, setting one, will remove the other.

**Comment by warpech** [comment]
The above was agreed between me and @tomalec on Hangouts.

**Comment by tomalec** [comment]
@lbustelo Sorry, that it took that long.
Starting from https://github.com/Juicy/juicy-html/releases/tag/2.0.0 you can use attributes and properties: `href` for URLs and `html` for inline content. So you no longer have to remember about `$=`
