### ISSUE TITLE
Problem with binding

### ISSUE THREAD

**Issue by sedestrian** [Juicy/juicy-html#22]
Hi, i am facing a problem to load html from a database and put it in an element through `<content>` and use that element in dom-repeat, i tried using your element to do this because passing the string to content doesn't work, but i ran into this problem:

if i try to use binding to set the value of content, the element displays nothing

the data in {{item.type}} is: 

`"<paper-button raised class='dragging white'>BUTTON</paper-button>"`

here is the code:
https://jsbin.com/buvigiw/edit?html,output

**Comment by warpech** [comment]
The JSBin code fails because of reasons not related to `juicy-html`. I can see that Polymer is not loaded at all in this bin. See the screenshot below.

This is the trick that we use to load Polymer in JSBin: http://jsbin.com/qezozor/1/edit?html,output

Can you please fix the JSBin? We will be glad to investigate.

![screen shot 2016-12-07 at 18 40 22](https://cloud.githubusercontent.com/assets/566463/20979309/bd3a8c02-bcac-11e6-81d1-381e63ddf232.png)

**Comment by tomalec** [comment]
As it seems to be a problem with loading Polymer itself. I'm closing this issue. Feel free to re-open if you still have some problems.
