### ISSUE TITLE
Juicy-html and Polymer 2.0

### ISSUE THREAD

**Issue by lcottret** [Juicy/juicy-html#25]
I used (with success) juicy-html with Polymer 1.8. I've just switched to Polymer 2.0.rc3. 
And I have this result:
TypeError: document.registerElement is not a function[En savoir plus]  data:%0A%20%20%20%20(function(scope)%20%7B%0A%20%20%20%20%20%20%20%20var%20JuicyHTMLPrototype%20%3D%:146:34
	<anonyme> http://127.0.0.1:8001/components/juicy-html/juicy-html.html.js:146:34
	<anonyme> http://127.0.0.1:8001/components/juicy-html/juicy-html.html.js:2:6

Does juicy-html have any compatibility problem with Polymer 2.0 ?

Version of juicy-html : 1.2.0
Version of polymer : 2.0.rc3
Version of navigator : Firefox 52.0 (64 bits)
OS : Ubuntu 16.04

**Comment by tomalec** [comment]
Thanks for feedback.
I suspect it's just the fact that it is vanilla JS custom element that uses Web Components V0 spec. Most probably it should work in Chrome which still have native V0 support, or if you run polyfill for v0 (together with webcomponentsjs v1) for example  https://github.com/WebReflection/document-register-element

Few months ago I have tried it, and it worked. But Polymer may change a lot since that time, so I cannot guarantee you anything.

However, we are planning to migrate all out juicy elements to V1 ASAP - most probably by the end of Q2 2017. Also `juicy-html` should be one of the first to migrate, as it acts as a foundation of most of our use-cases.

**Comment by warpech** [comment]
Archiving as using Custom Elements v1 API is tracked in #27. Please subscribe to that issue. Thanks
